export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const FETCH_SCHOOLLIST_REQUEST = 'FETCH_SCHOOLLIST_REQUEST';
export const FETCH_SCHOOLLIST_SUCCESS = 'FETCH_SCHOOLLIST_SUCCESS';
export const FETCH_SCHOOLLIST_ERROR = 'FETCH_SCHOOLLIST_ERROR';
export const CLEAR_SCHOOLLIST_REQUEST = 'CLEAR_SCHOOLLIST_REQUEST';

export const FETCH_SCHOOLDETAIL_REQUEST = 'FETCH_SCHOOLDETAIL_REQUEST';
export const FETCH_SCHOOLDETAIL_SUCCESS = 'FETCH_SCHOOLDETAIL_SUCCESS';
export const FETCH_SCHOOLDETAIL_ERROR = 'FETCH_SCHOOLDETAIL_ERROR';
export const CLEAR_SCHOOLDETAIL_REQUEST = 'CLEAR_SCHOOLDETAIL_REQUEST';

export const FETCH_HOUSELIST_REQUEST = 'FETCH_HOUSELIST_REQUEST';
export const FETCH_HOUSELIST_SUCCESS = 'FETCH_HOUSELIST_SUCCESS';
export const FETCH_HOUSELIST_ERROR = 'FETCH_HOUSELIST_ERROR';

export const BARODE_SCANLABEL_REQUEST = 'BARODE_SCANLABEL_REQUEST';
export const BARODE_SCANLABEL_SUCCESS = 'BARODE_SCANLABEL_SUCCESS';
export const BARODE_SCANLABEL_ERROR = 'BARODE_SCANLABEL_ERROR';
export const CLEAR_BARODE_SCANLABEL = 'CLEAR_BARODE_SCANLABEL';

export const STORAGE_CREATE_REQUEST = 'STORAGE_CREATE_REQUEST';
export const STORAGE_CREATE_SUCCESS = 'STORAGE_CREATE_SUCCESS';
export const STORAGE_CREATE_ERROR = 'STORAGE_CREATE_ERROR';
export const CLEAR_STORAGE_CREATE = 'CLEAR_STORAGE_CREATE';

export const GET_REPORT_STATUS_REQUEST = 'GET_REPORT_STATUS_REQUEST';
export const GET_REPORT_STATUS_SUCCESS = 'GET_REPORT_STATUS_SUCCESS';
export const GET_REPORT_STATUS_ERROR = 'GET_REPORT_STATUS_ERROR';
export const CLEAR_GET_REPORT_STATUS_ = 'CLEAR_GET_REPORT_STATUS_';

export const UPLOAD_IMAGES_REQUEST = 'UPLOAD_IMAGES_REQUEST';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
export const UPLOAD_IMAGES_ERROR = 'UPLOAD_IMAGES_ERROR';
export const CLEAR_UPLOAD_IMAGES = 'CLEAR_UPLOAD_IMAGES';

export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST';
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS';
export const LOCATION_LIST_ERROR = 'LOCATION_LIST_ERROR';
export const CLEAR_LOCATION_LIST = 'CLEAR_LOCATION_LIST';

export const NAME_LIST_REQUEST = 'NAME_LIST_REQUEST';
export const NAME_LIST_SUCCESS = 'NAME_LIST_SUCCESS';
export const NAME_LIST_ERROR = 'NAME_LIST_ERROR';
export const CLEAR_NAME_LIST = 'CLEAR_NAME_LIST';

export * from './auth/actions';
